spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      #      ddl-auto: update
      ddl-auto: none
    show-sql: true

spring-doc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true