cors:
  originPatters: http://localhost:3000,http://localhost:8080,https://www.google.com.br
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 900000 # fifteen minutes
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      #      ddl-auto: update
      ddl-auto: none
    show-sql: true

spring-doc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    path: /api/swagger-ui.html
